categories:
  - title: 'Mudanças incompatíveis'
    label: 'breaking-change'
  - title: 'Bugs Resolvidos'
    label: 'bug'
  - title: 'Novas Features'
    label: 'feature'
  - title: 'Documentação'
    label: 'docs'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
version-resolver:
  minor:
    labels:
      - 'breaking-change'
  patch:
    labels:
      - 'feature'
      - 'bug'
  default: patch
template: |
  ## Changelog for $RESOLVED_VERSION

  $CHANGES

  Docs: https://github.com/async-worker/aiologger/

  Commits: https://github.com/async-worker/aiologger/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
  Tag: https://github.com/async-worker/aiologger/releases/tag/$RESOLVED_VERSION
