name: pull-request

on: pull_request


jobs:
  tests:
    name: unittests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", 3.x]
    steps:
      - name: install {libxml2,libxslt}-dev
        run: sudo apt-get install libxml2-dev libxslt-dev

      - name: checkout
        uses: actions/checkout@v2

      - name: Install python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}

      - name: Install pip/pipenv
        run: pip install -U pip pipenv

      - name: Install aiologer
        run: pipenv install --system --deploy --ignore-pipfile --dev

      - name: pipenv run test
        run: pipenv run test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pip/pipenv
        run: pip install -U pip pipenv

      - name: Install aiologer
        run: pipenv install --system --deploy --ignore-pipfile --dev

      - name: pipenv run lint
        run: pipenv run lint

  fmt-check:
    name: fmt-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pip/pipenv
        run: pip install -U pip pipenv

      - name: Install aiologer
        run: pipenv install --system --deploy --ignore-pipfile --dev

      - name: pipenv run fmt-check
        run: pipenv run fmt-check
